name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world
    - name: Test
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update -yq
        sudo apt install -yq zlib1g-dev libssl-dev:i386 zlib1g-dev:i386
        git clone https://github.com/jackpal/Android-Terminal-Emulator.git
        cd Android-Terminal-Emulator
        ./gradlew assembleRelease
